create table farmers_market
(
    FMID          INTEGER
        constraint farmers_market_pk
            primary key,
    MarketName    TEXT,
    Website       TEXT,
    Facebook      TEXT,
    Twitter       TEXT,
    Youtube       TEXT,
    OtherMedia    TEXT,
    street        TEXT,
    city          TEXT,
    County        TEXT,
    State         TEXT,
    zip           TEXT,c
    Season1Date   TEXT,
    Season1Time   TEXT,
    Season2Date   TEXT,
    Season2Time   TEXT,
    Season3Date   TEXT,
    Season3Time   TEXT,
    Season4Date   TEXT,
    Season4Time   TEXT,
    LAT           REAL,
    LON           REAL,
    Location      TEXT,
    Credit        INTEGER,
    WIC           INTEGER,
    WICcash       INTEGER,
    SFMNP         INTEGER,
    SNAP          INTEGER,
    Organic       INTEGER,
    Bakedgoods    INTEGER,
    Cheese        INTEGER,
    Crafts        INTEGER,
    Flowers       INTEGER,
    Eggs          INTEGER,
    Seafood       INTEGER,
    Herbs         INTEGER,
    Vegetables    INTEGER,
    Honey         INTEGER,
    Jams          INTEGER,
    Maple         INTEGER,
    Meat          INTEGER,
    Nursery       INTEGER,
    Nuts          INTEGER,
    Plants        INTEGER,
    Poultry       INTEGER,
    Prepared      INTEGER,
    Soap          INTEGER
                      Trees INTEGER,
    Wine          INTEGER,
    Coffee        INTEGER,
    Beans         INTEGER,
    Fruits        INTEGER,
    Grains        INTEGER,
    Juices        INTEGER,
    Mushrooms     INTEGER,
    PetFood       INTEGER,
    Tofu          INTEGER,
    WildHarvested INTEGER,
    updateTime    TEXT
);

SELECT COUNT(*) FROM farmers_market;

SELECT * FROM farmers_market LIMIT 10